version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - id: azad
    main: ./cmd/azad
    binary: azad
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - completions/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: aliyzl
    name: terminal-azadi
  name_template: "Azad v{{.Version}}"

brews:
  - repository:
      owner: aliyzl
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/aliyzl/terminal-azadi
    description: "Beautiful terminal VPN client — one command to connect to the fastest server"
    license: MIT
    skip_upload: "{{ if .IsSnapshot }}true{{ end }}"
    test: |
      system "#{bin}/azad", "--version"
    extra_install: |-
      bash_completion.install "completions/azad.bash" => "azad"
      zsh_completion.install "completions/azad.zsh" => "_azad"
      fish_completion.install "completions/azad.fish"

nfpms:
  - id: azad-linux
    package_name: azad
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: aliyzl
    homepage: https://github.com/aliyzl/terminal-azadi
    maintainer: aliyzl
    description: "Beautiful terminal VPN client — one command to connect to the fastest server"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: completions/azad.bash
        dst: /usr/share/bash-completion/completions/azad
      - src: completions/azad.zsh
        dst: /usr/share/zsh/vendor-completions/_azad
      - src: completions/azad.fish
        dst: /usr/share/fish/vendor_completions.d/azad.fish

# AUR_KEY SSH private key must be configured as a CI secret
aurs:
  - name: azad-bin
    homepage: https://github.com/aliyzl/terminal-azadi
    description: "Beautiful terminal VPN client — one command to connect to the fastest server"
    maintainers:
      - "aliyzl"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/azad-bin.git"
    skip_upload: "{{ if .IsSnapshot }}true{{ end }}"
    package: |-
      install -Dm755 "./azad" "${pkgdir}/usr/bin/azad"
      install -Dm644 "./completions/azad.bash" "${pkgdir}/usr/share/bash-completion/completions/azad"
      install -Dm644 "./completions/azad.zsh" "${pkgdir}/usr/share/zsh/site-functions/_azad"
      install -Dm644 "./completions/azad.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/azad.fish"

# Classic confinement requires manual Snap Store review (can take days/weeks)
snapcrafts:
  - name: azad
    summary: "Beautiful terminal VPN client"
    description: "One command to connect to the fastest VPN server through a stunning terminal interface"
    grade: stable
    confinement: classic
    license: MIT
    publish: true
