version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - id: azad
    main: ./cmd/azad
    binary: azad
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - completions/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: leejooy96
    name: azad
  name_template: "Azad v{{.Version}}"

brews:
  - repository:
      owner: leejooy96
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/leejooy96/azad
    description: "Beautiful terminal VPN client — one command to connect to the fastest server"
    license: MIT
    skip_upload: "{{ if .IsSnapshot }}true{{ end }}"
    test: |
      system "#{bin}/azad", "--version"
    extra_install: |-
      bash_completion.install "completions/azad.bash" => "azad"
      zsh_completion.install "completions/azad.zsh" => "_azad"
      fish_completion.install "completions/azad.fish"

nfpms:
  - id: azad-linux
    package_name: azad
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: leejooy96
    homepage: https://github.com/leejooy96/azad
    maintainer: leejooy96
    description: "Beautiful terminal VPN client — one command to connect to the fastest server"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: completions/azad.bash
        dst: /usr/share/bash-completion/completions/azad
      - src: completions/azad.zsh
        dst: /usr/share/zsh/vendor-completions/_azad
      - src: completions/azad.fish
        dst: /usr/share/fish/vendor_completions.d/azad.fish
